### ISSUE TITLE
Eagle files?

### ISSUE THREAD

**Issue by steveheinsch** [3drobotics/Pixhawk_OS_Hardware#1]
I don't have Altium designer or anything else that will convert these files to Eagle, or other freeware program. Is it possible to provide them in additional formats?

**Comment by proficnc** [comment]
No, these files were all done originally in Altium. Eagle is not free either....

The full schematics and Gerbers are supplied.  

Also, these drawings are out of date.

Pixhawk2 will be on sale starting from June to the general public, up to date drawings will be released when these hit the market.

Any questions, feel free to join the conversation at the Pixhawk 2 Facebook page, or Twitter etc, or jump on drones discuss Google groups.

If your a manufacturer that wishes to support the project, feel free to contact me, and I will be happy to work with you if your willing to support the project.
